### ISSUE TITLE
Decide for a name?

### ISSUE THREAD

**Issue by Mec-iS** [HTTP-APIs/hydra-cg-statute#1]
In the current draft I added "Hydra-CG" as a placeholder. We can keep this or look for options.

Possible options:
* HTTP Hydra
* Hydra REST
* Hydra HTTP-APIs

**Comment by de-sh** [comment]
We are working on APIs right, so Hydra HTTP-APIs or Hydra APIs seems like the best option.

**Comment by xadahiya** [comment]
Finalized HydraEcosystem

**Comment by xadahiya** [comment]
@Mec-iS please close this
